#!/bin/sh

SLUG="TheContext/episodes"
JDK="oraclejdk8"
BRANCH="master"

if [ "$TRAVIS_REPO_SLUG" != "$SLUG" ]; then
  echo "Skipping deployment: wrong repository. Expected '$SLUG' but was '$TRAVIS_REPO_SLUG'."
elif [ "$TRAVIS_JDK_VERSION" != "$JDK" ]; then
  echo "Skipping deployment: wrong JDK. Expected '$JDK' but was '$TRAVIS_JDK_VERSION'."
elif [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  echo "Skipping deployment: was pull request."
elif [ "$TRAVIS_BRANCH" != "$BRANCH" ]; then
  echo "Skipping deployment: wrong branch. Expected '$BRANCH' but was '$TRAVIS_BRANCH'."
else

  # checkout repos where to push generated things
  git clone https://github.com/artem-zinnatullin/TheContext-Podcast.git # foldername TheContext-Podcast
  git clone https://github.com/TheContext/website # foldername website

  # Generate stuff
  java -jar podcaster.jar --input .. --output-feed TheContext-Podcast/feed.rss --output-website website/content/episodes

  # Push generated feed.rss
  cd TheContext-Podcast
  git add .
  git commit -am "Autogenerated feed"
  git push https://$ACCESS_TOKEN:x-oauth-basic@github.com/artem-zinnatullin/TheContext-Podcast.git master

  # Push website
  cd ../website
  git add .
  git commit -am "Autogenerated website"
  git push https://$ACCESS_TOKEN:x-oauth-basic@github.com/TheContext/episodes.git master

  # Clean up
  cd ..
  rm -rf website
  rm -rf TheContext-Podcast

  echo "Deployed!"
fi